USE DATABASE SYNGENTA;
USE SCHEMA PDF_PROCESSING;

-- Recreate the Streamlit app with the updated files from STREAMLIT_STAGE
CREATE OR REPLACE STREAMLIT GWAS_TRAIT_VIEWER
    FROM '@SYNGENTA.PDF_PROCESSING.STREAMLIT_STAGE/'
    MAIN_FILE = 'streamlit_app.py'
    RUNTIME_NAME = 'SYSTEM$ST_CONTAINER_RUNTIME_PY3_11'
    COMPUTE_POOL = CPU_X64_XS
    QUERY_WAREHOUSE = DEMO_JGH
    EXTERNAL_ACCESS_INTEGRATIONS = (PYPI_ACCESS_INTEGRATION);

-- Publish the live version
ALTER STREAMLIT GWAS_TRAIT_VIEWER ADD LIVE VERSION FROM LAST;


